# ===============================
# APPLICATION
# ===============================
spring.application.name=user-service
server.port=8081


# ===============================
# POSTGRESQL DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/user-service
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# ACTUATOR (Monitoring)
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

# Security/JWT Configuration
jwt.secret: ${JWT_SECRET:L8KwmXTT/ByT7e9ZiO0s5cGedE7cSfS5YKpC0Qn/qO8=}
jwt.expiration: 86400
jwt.refreshExpiration: 172800